[WIP] Ctb 95 filters for stock chart
PZ-CTB/ctb-frontend pull request #17
Opened 2023-04-18 10:50 UTC by BlabberMobsterYeast

2023-04-18 20:14 UTC, krystiansledz requested changes
Działało, ale nie do końca tak jak powinno, sporo kodu do wyrzucenia i kilka poprawek

W komentarzach starałem się opisać wszystko dokładnie krok po kroku więc idź od góry do dołu 😄 

Rozwiązane problemy:
- brak walidacji
- brak domyślnych wartości w URL'u po wejściu na stronę
- problemy z datą

Do zapamiętania na przyszłość:
- jeżeli mamy globalny stan np. URL to nie musimy przekazywać go ani funkcji, które go modyfikują pomiędzy jakimikolwiek komponentami 
- wszystkie wartości i zmiany formularza są obsługiwane przez `react-hook-form`
- jak mamy kod, który wygląda dokładnie tak samo w dwóch miejscach, a przy tym korzysta z zewnętrznego hooka to najlepiej zrobić z tego osobny customowy hook, który będzie używany w tych miejscach

2023-04-18 20:14 UTC, krystiansledz commented on package.json
> +    "qs": "^6.11.1",
Nie używasz nigdzie

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
> +    data[0].high !== undefined;
Możemy w sumie przestać wyświetlać wykres jeżeli nie ma żadnych danych dla niego - ktoś ustawił złe filtry

Przenieś to tylko pod `useChartParams` bo inaczej będzie problem z hookami

```suggestion
  if (data.length === 0)
    return <Typography>No data - please adjust your filters.</Typography>;

  const isAggregate =
    data[0].low !== undefined &&
    data[0].high !== undefined;
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
> +  const highestChartValue = Math.max(...data.map((d) => d.high ?? d.avg), 0);
Domyślam się, że dodałeś 0 dla sytuacji gdy nie ma danych do wyświetlenia, ale teraz już nie będziemy wyświetlać pustego wykresu

```suggestion
  const lowestChartValue = Math.min(...data.map((d) => d.low ?? d.avg));
  const highestChartValue = Math.max(...data.map((d) => d.high ?? d.avg));
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
To możesz przenieść między `export default StockChart` a `const Container`

2023-04-18 20:14 UTC, krystiansledz commented on src/app/index.tsx
> +    <QueryParamProvider adapter={ReactRouter6Adapter}>
Przenieś ten Provider do `src/providers/index.tsx` na samą górę -  między `return (` a `<RQueryClientProvider>`

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/index.tsx
> +  setQuery;
Dodaj do `.eslintrc` nową regułę `"no-unused-expressions": "error",` - pod `"no-console": "warn",`

Dzięki temu w przyszłości nie zapomnimy usuwać takich rzeczy, bo nie ma żadnego warninga/errora na to, jedyne co widzę w swoim IDE (Webstorm) to podpowiedź

```suggestion
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/index.tsx
> +  });
Kolejne komentarze potraktuj jako jedna całość. Postaram się to tutaj opisać:

`+` fajna ta paczka `use-query-params`, łatwo się z niej korzysta


`---` mamy dokładnie taki sam kod w dwóch miejscach, tutaj oraz w `src/app/dashboard/components/filters/form.tsx`, więc możemy z tego zrobić hook'a
`--` nie mamy domyślnych wartości w URL, a to URL ma przechowywać cały stan i to z niego mamy pobierać i tam trzymać wartości - to on jest naszym "context'em/całym stanem"
`-` po zmianie wartości pushuje się nowy url do stosu całej historii, więc user po kliknięciu strzałki do tyłu nie cofa się do wcześniejszej strony tylko do wcześniejszego stanu filtrów - rozwiązaniem jest `{ updateType: 'replace' }`

```suggestion
  const [query] = useFiltersQueryParams();
  
  // w `src/app/dashboard/utils.ts`
  
  export const useFiltersQueryParams = () => {
    const defaultValues = getFilterFormDefaultValues();

    return useQueryParams({
      date_from: withDefault(
        StringParam,
        defaultValues.startDate.format('YYYY-MM-DD')
      ),
      date_to: withDefault(
        StringParam,
        defaultValues.endDate.format('YYYY-MM-DD')
      ),
      aggregate: withDefault(NumberParam, defaultValues.aggregate),
  }, { updateType: 'replace' });
};
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/index.tsx
> +  const [aggregate, setAggregate] = useState(query.aggregate ?? 1);
Nie musimy tego przechowywać w osobnych state'ach - od tego jest `query`

```suggestion
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/index.tsx
> +      />
Nie potrzebujemy tego przekazywać niżej - od tego mamy `query` i `setQuery`

```suggestion
      <StockChartFiltersForm/>
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/index.tsx
> +      <StockChart data={getDataFromServer(startDate, endDate, aggregate)} />
W `query` mamy `string` więc obecnie chcemy przekazać tam object `Dayjs`

Ogólnie to jak będziemy się łączyć z backendem to wszystko będzie do wywalenia (łącznie z funkcją `getDataFromServer`), ale na teraz to wystarczy żeby działało

```suggestion
      <StockChart data={getDataFromServer(dayjs(query.date_from),  dayjs(query.date_to), aggregate)} />
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +const StockChartFiltersForm = (props: Props) => {
To już nie jest potrzebne, bo niczego do filtrów nie przekazujemy

```suggestion
const StockChartFiltersForm = () => {
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +  });
Mamy teraz hooka, żeby nie duplikować kodu

```suggestion
  const [query, setQuery] = useFiltersQueryParams()
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +  }
Nic nie musimy przekazywać do parenta, będziemy zaraz edytować `query` z tego poziomu i to wystarczy

```suggestion
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
>        />
`onChange` oraz `value` są obsługiwane przez `react-hook-form`, będziemy się do nich dostawać używając `useWatch`

```suggestion
    <StyledForm methods={methods}>
      <DateInput
        name="startDate"
        label="Start Date"
        minDate={minDateBoundary}
        maxDate={endDate}
      />
      <DateInput
        name="endDate"
        label="End Date"
        minDate={startDate}
        maxDate={today}
      />
      <NumberInput
        name={'aggregate'}
        label={'aggregate'}
        inputProps={{ min: 1, max: 100, step: 1 }}
      />
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +    },
No i teraz zaczynamy zabawę z aktualizowaniem wartości formularza oraz z aktualizowaniem query.

1. Domyślne wartości są pobierane z `query`

```suggestion
    defaultValues: {
      startDate: dayjs(query.date_from),
      endDate: dayjs(query.date_to),
      aggregate: query.aggregate,
    },
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +  const { handleSubmit, control, setValue } = methods;
2. Nie potrzebujemy `setValue` - wartości formularza automatycznie się aktualizują z wykorzystaniem `react-hook-form`
3. Nie potrzebujemy funkcji `handleSubmit`, bo nie mamy żadnego submit button'a więc też do StyledForm'a nie przekazujemy onSubmit, co za tym idzie trzeba poprawić type Props'ów - `onSubmit?: FormProps['onSubmit'];` - zmiana na opcjonalny
4. Jeżeli nie mamy submit buttona to tracimy walidację, więc wyciągniemy sobie pomocną funkcję z `rhf` - `trigger`, zaraz jej użyjemy

 https://react-hook-form.com/api/useform/trigger/

```suggestion
  const { control, trigger } = methods;
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
>    const onSubmit = handleSubmit((data: FiltersForm) => {
```suggestion
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +  }, [debouncedAggregate]);
5. Chcemy aktualizować `query` po jakiejkolwiek zmianie formularza, ale też tylko wtedy kiedy walidacja formularza przebiegnie pomyślnie
6. Zapewnia nam to też wrzucenie domyślnych wartości do URL podczas pierwszego wejścia na tą stronę np. po zalogowaniu lub przejściu z http://localhost:3000/app/statistics

```suggestion
   useEffect(() => {
    trigger().then((isValid) => {
      if (!isValid) return;

      setQuery({
        aggregate: debouncedAggregate,
        date_to: endDate.format('YYYY-MM-DD'),
        date_from: startDate.format('YYYY-MM-DD'),
      });
    });
  }, [debouncedAggregate, startDate, endDate]);
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/form.tsx
> +}
Wydaje mi się, że wszystko działa prawidłowo bez jakiegokolwiek konwertowania w tym momencie

```suggestion
```

2023-04-18 20:14 UTC, krystiansledz commented on src/app/dashboard/components/filters/schema.ts
> +    aggregate: z.number(),
Pamiętaj o tym 😄

2023-04-25 05:55 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
nie rozumiem co ani po co xd

2023-04-25 06:32 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
const Linetype, stała która nie odnosi się do stanu komponentu może być wyrzucona poza komponent

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/filters/schema.ts
> +    aggregate: z.number(),
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/filters/form.tsx
> +  }, [debouncedAggregate]);
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/filters/form.tsx
>    const onSubmit = handleSubmit((data: FiltersForm) => {
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/filters/form.tsx
> +  const { handleSubmit, control, setValue } = methods;
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/index.tsx
> +    <QueryParamProvider adapter={ReactRouter6Adapter}>
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
> +  const highestChartValue = Math.max(...data.map((d) => d.high ?? d.avg), 0);
fixed

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
> +    data[0].high !== undefined;
Poprawiłem kod, poza "Przenieś to tylko pod useChartParams bo inaczej będzie problem z hookami"
Jakie problemy z hookami masz na myśli?

2023-04-25 06:50 UTC, BlabberMobsterYeast commented on package.json
> +    "qs": "^6.11.1",
fixed

2023-04-25 06:52 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
komponent odnosi się do tej stałej:
 <Line
            name={isAggregate ? 'Average price' : 'Price'}
            **type={lineType}**
            dataKey="avg"
            stroke={theme.palette.primary.main}
          />

2023-04-25 06:53 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/filters/form.tsx
> +}
tak, usunałem tę funkcje

2023-04-25 07:04 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
> +    data[0].high !== undefined;
https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

"Don’t call Hooks inside loops, conditions, or nested functions. Instead, always use Hooks at the top level of your React function, before any early returns."

więc `return <Typography>....` jest właśnie zaliczany jako "early return"

2023-04-25 07:05 UTC, krystiansledz commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
Tak, ale stała nie korzysta ze stanu komponentu, więc takie stałe mogą być wyrzucone poza ciało komponentu dzięki czemu nie są liczone przy każdym renderze komponentu

2023-04-25 12:06 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
>    const lineType = 'linear';
ok, poprawiłem

2023-04-25 12:06 UTC, BlabberMobsterYeast commented on src/app/dashboard/components/chart/index.tsx
> +    data[0].high !== undefined;
ok, poprawiłem

2023-04-26 07:57 UTC, merged