[WIP] Ctb-31-TextInput
PZ-CTB/ctb-frontend pull request #4
Opened 2023-03-11 11:22 UTC by sakor88

Wrzuciłem to co na razie udało mi się zrobić na brancha test-Jakub. Borykam się na razie z problemem polegającym na tym, że wywala mi error jak coś wpiszę w pole tekstowe, bo zmienia się jego stan (?) a tak nie może być czy coś jeśli cokolwiek z tego rozumiem. Poza tym, w TextFieldProps wrzuciłem też control, bo z tego co rozumiem za pomocą tego ma się komunikować web-hooks i mui (?). Jak będziesz miał chwilę rzuć proszę okiem

2023-03-11 12:19 UTC, krystiansledz requested changes
Wszystko opisane w komentarzach, powinieneś ogarnąć 😄

2023-03-11 12:19 UTC, krystiansledz commented on package.json
> +    "yup": "^1.0.2",
Nie potrzebujemy już `yup'a`

```suggestion
```

2023-03-11 12:19 UTC, krystiansledz commented on src/components/textInput/index.tsx
> +export default TextInput
1. `name` nie może przyjmować tylko dwóch wartości "email" lub "password" - chcemy, żeby był to `string`, bo wtedy możemy przekazać inne nazwy danego pola np. `confirmPassword` w przyszłości

2. Nie potrzebujemy tutaj `control` ponieważ `Form` jest używany z `FormContextProvider` który przekazuje do wszystkich inputów wewnątrz niego odpowiedni `control`

3. Nigdzie nie chcemy `any` w TypeScriptcie 

4. Skorzystaj z `fieldState.error` który ma w sobie pole `message`. W połączeniu z [TextField](https://mui.com/material-ui/react-text-field/#validation) możemy wykorzystać niektóre props'y żeby pokolorować input na czerwono oraz żeby dać wiadomość poniżej

```suggestion
import { TextField, TextFieldProps } from '@mui/material'
import { Controller } from 'react-hook-form'

type Props = TextFieldProps & {
  name: string
  label: string
}

const TextInput = function (props: Props) {
  const { name, label, ...textFieldProps } = props

  return (
    <Controller
      name={name}
      render={({ field: { onChange, value }, fieldState: {error} }) => (
        <TextField
          onChange={onChange}
          value={value}
          label={label}
          ... // tutaj coś trzeba dodać z wykorzystaniem `error`
          {...textFieldProps}
        />
      )}
    />
  )
}

export default TextInput
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/index.tsx
> +      <LoginPage></LoginPage>
Jeżeli nie przekazujemy żadnego `children` wewnątrz komponentu to powinniśmy go od razu zamykać
```suggestion
      <LoginPage/>
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/login/index.tsx
> +  const { handleSubmit, control } = methods
```suggestion
  const { handleSubmit } = methods
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/login/index.tsx
> +      <TextInput name="email" label="Email" control={control} />
```suggestion
      <TextInput name="email" label="Email" />
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/login/schema.ts
> +import * as zod from 'zod'
```suggestion
import { z } from 'zod'
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/login/schema.ts
> +    .min(8, { message: 'Too short - min. 8 characters' }),
1. Domyślnie `zod` ustawia wszystkie pola jako `required`, `nonempty` odnosi się do typu `array`, którego tutaj nie mamy 
2. Domyślnie `zod` ustawia `required_error` na "Required", jeżeli chcesz zmienić to na "This is required" musisz do stringa wrzucić {required_error: "...."}. Możemy zostawić "Required" lub zmienić na "This is required", mi obojętnie, wybierz co wolisz.

```suggestion
  export const LoginFormSchema = z.object({
  email: z
    .string({ required_error: 'This is required' })
    .email({ message: 'Must be a valid email' }),
  password: z
    .string({ required_error: 'This is required' })
    .min(8, { message: 'Too short - min. 8 characters' }),
})
```

2023-03-11 12:19 UTC, krystiansledz commented on src/sandbox/jakub/login/index.tsx
>      reValidateMode: 'onSubmit',
Jeżeli miałeś na myśli ten error w konsoli: `A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

Dzieje się tak dlatego, że domyślnie wszystkie wartości są `undefined` i jak zaczynamy coś wpisywać to zmieniają się na `defined -> string` dlatego jest ten warning.
Żeby temu zapobiec możemy dodać `defaultValues` do `useForm()`, gdzie `defaultValues` musi być obiektem o typie `LoginForm`
Możesz stworzyć plik `/login/utils.ts` w którym będzie funkcja `getLoginFormDefaultValues()`, która będzie zwracała obiekt o typie `LoginForm`, gdzie domyślnymi wartościami będą puste stringi : `""`

```suggestion
  const methods = useForm<LoginForm>({
    defaultValues: getLoginFormDefaultValues(),
    reValidateMode: 'onSubmit',
    ...
```

2023-03-12 22:50 UTC, sakor88 commented
Wrzuciłem wersję, w której działa już wyświetlanie błędu jak się coś wpisze i kliknie enter, ale nie działa po kliknięciu submit. Nie za bardzo wiem jak do tego dalej podejść

2023-03-13 09:22 UTC, krystiansledz requested changes
Żeby button "Submit" działał to musisz dać mu typ "submit", bo domyślnie jest "button"

`<Button type="submit">Submit</Button>`

2023-03-13 09:22 UTC, krystiansledz commented on src/sandbox/jakub/login/index.tsx
> +    defaultValues: getLoginFormDefaultValues,
```suggestion
    defaultValues: getLoginFormDefaultValues(),
```

2023-03-13 09:22 UTC, krystiansledz commented on src/sandbox/jakub/login/utils.ts
> +export default getLoginDefaultValues()
```suggestion
export const getLoginDefaultValues = (): LoginForm => {
  return { email: '', password: '' }
}
```

2023-03-13 18:27 UTC, krystiansledz approved these changes
Lgtm :)

2023-03-13 18:27 UTC, krystiansledz commented on src/sandbox/jakub/login/index.tsx
> +      <Button type={'submit'}>Submit</Button>
```suggestion
      <Button type="submit">Submit</Button>
```

2023-03-13 18:35 UTC, merged